site_name: Tábata de Faria
theme:
 name: material
 palette:
    scheme: slate
    primary: pink
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg